name: Purge jsDelivr

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            js/**
            css/**

      - name: Purge changed assets on jsDelivr
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          BASE="https://purge.jsdelivr.net/gh/foreverr-id/dash-assets@main"
          for f in ${{ steps.changes.outputs.all_changed_files }}; do
            echo "Purging $f"
            curl -fsSL "$BASE/$f" || true
          done